config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :notifications, only: [ :destroy, :index ]

  resources :parking_spots do
    resources :bookings do
      resources :payments, only: [:new, :create]
    end
  end

  resources :bookings, only: [:index] do
    member do
      get "rejected"
      get 'accepted' => 'payments#accepted'
    end
      resource :chat_rooms, only: [:show]
      resources :reviews, only: [:new, :create]
  end

  get '/management' => 'users#management'
  get '/profile' => 'users#show', as: :profile
  get '/search' => 'parking_spots#search'
  mount ActionCable.server => '/cable'

end

app/models/booking.rb
class Booking < ApplicationRecord

#actives records relationships
  belongs_to :parking_spot
  belongs_to :user
  has_many :reviews
  has_one :chat_room
  has_one :owner, through: :parking_spot, source: :user

#allow stripe
  monetize :total_price_cents

#validations
  validates :start_at, presence: :true
  validates :end_at, presence: :true
  validate :booking_period_not_overlapped, on: :create

#chat room creation
  after_create :create_associated_chatroom

enum status: [:pending, :rejected, :accepted, :paid]


  def n_of_days
    if (self.end_at || self.start_at) == nil
    else
      total_days = (self.end_at.to_date - self.start_at.to_date) + 1
    end
  end

  def t_price
    if (self.end_at || self.start_at) == nil
    else
      n_of_days * self.parking_spot.price_cents
    end
  end

  def self.sum_price
      sum(:total_price_cents)
  end

  private

# Creates chatroom for each booking
  def create_associated_chatroom
    ChatRoom.create(booking_id: self.id)
  end

# check that it's not overlapping with another booking.
  def booking_period_not_overlapped
    parking_spot = self.parking_spot
    unless parking_spot.bookings.where(
      '(start_at <= ? AND end_at >= ?) OR (start_at >= ? AND start_at <= ?)',
      start_at, start_at,
      start_at, end_at
      ).empty?
      errors.add(:start_at, 'Parking already book at this period. Please choose another')
    end
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_parking_spot , except: [:index, :rejected, :accepted]
  before_action :find_booking , only: [:rejected, :accepted, :show]

  def index
    @user = current_user
    @bookings = Booking.paginate(:page => params[:page], :per_page => 8)
  end

  def new
    @booking = Booking.new
  end

  def show

      #@booking = Booking.where(status: 'paid').find(params[:id])

    # @booking = Booking.find_by_id_and_parking_spot_id(params[:id], @parking_spot.id)

  end

  def create
    @booking = current_user.bookings.build(booking_params)
    @booking.parking_spot_id = params[:parking_spot_id]
    @booking.total_price_cents = @booking.t_price
    @booking.number_of_days = @booking.n_of_days

    if @booking.save

      owner = @booking.parking_spot.user
      ownerr = owner.notifications.build(content: "You have a new booking for #{ view_context.link_to @booking.parking_spot.city, parking_spot_path(@booking.parking_spot.id), style: "color: #4CAF50" }, #{view_context.link_to "manage", management_path, style: "color:#4CAF50" } it" )

      if ownerr.save
        respond_to do |format|
        flash[:notice] = "Notifications"
        format.html
        format.js
        end
      end

      flash[:notice] = "Thank you for booking, Your booking time start at #{@booking.start_at} and ends at #{@booking.end_at} Your total price is: #{@booking.total_price}"
      redirect_to new_parking_spot_booking_payment_path(@parking_spot, @booking)
    else
      render :new
    end
  end

  def rejected
     # security
    if current_user.id == @booking.parking_spot.user.id && @booking.rejected!


      book = @booking.user
      bookk = book.notifications.create(content: "You have a new booking #{@booking.id}, for #{@booking.parking_spot.city}")


      respond_to do |format|
        format.html { redirect_to parking_spot_path(@booking.parking_spot), flash[:notice] = "Booking Rejected" }
        format.js  # <-- will render `app/views/bookings/rejected.js.erb`
      end
    end
  end

  def accepted
    # security
    if current_user.id == @booking.parking_spot.user.id && @booking.accepted!

      respond_to do |format|
        format.html { redirect_to parking_spot_path(@booking.parking_spot), flash[:notice] = "Booking Accepted" }
        format.js  # <-- will render `app/views/bookings/accepted.js.erb`
      end
    end
    #@booking.accepted!
    #redirect_to parking_spot_path(@booking.parking_spot)
    #flash[:notice] = "Booking Accepted"
  end

  private

  def find_parking_spot
    @parking_spot = ParkingSpot.find(params[:parking_spot_id])
  end

  def booking_params
    params.require(:booking).permit(:start_at, :end_at)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/views/bookings/_access.html.erb
<p>
  <%= link_to accepted_booking_path(@booking), remote: true, class: "booking-confirm-#{@booking.id}", style: "color:red" do %>
    Confirmed
  <% end %>
<p>

app/views/bookings/_cashspent.html.erb
    <div class="row py3">
      <div class="col-xs-12 col-md-6">
        <h2><strong>Cash spent: </strong><%= humanized_money_with_symbol(current_user.bookings.sum_price) %></h2>
      </div>
      <div class="col-xs-12 col-md-6">
        <h2><strong>Total bookings: </strong><%= current_user.bookings.count %></h2>
      </div>
    </div>

app/views/bookings/_show.html.erb
<p>
  <%= link_to rejected_booking_path(@booking), remote: true, class: "booking-cancel-#{@booking.id}", style: "color:red" do %>
    Cancelled
  <% end %>
<p>

app/views/bookings/accepted.js.erb
$('.booking-<%= @booking.id %>').remove();

$('.booking-confirm-<%= @booking.id %>').hide();

var new_confirm = $("<%= j render 'bookings/show', booking: @booking %>")
$('.confirm').append(new_confirm);

app/views/bookings/confirm.html.erb
<div class="container text-center">
  <h1>You have to pay: <%= @booking.total_price %>$</h1>
</div>

app/views/bookings/destroy.html.erb
<h1>Booking#destroy</h1>
<p>Find me in app/views/booking/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Booking#edit</h1>
<p>Find me in app/views/booking/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container user_dashboard">
  <%= render 'cashspent' %>
  <div class="row mb2">
    <div class="col-xs-12 col-md-8 col-lg-8 py2" style="border: 1px solid grey;">
      <h2>Current bookings</h2>
        <hr>
        <% @bookings.each_with_index do |booking, index| %>
          <% if booking.start_at <= Date.today || booking.start_at > Date.today  && booking.end_at > Date.today %>
            <div class="col-md-4">
              <p><strong>Address: </strong><%= booking.parking_spot.street_address.titleize %></p>
              <p><strong>Starts: </strong><%= booking.start_at %></p>
              <p> <strong>Ends:</strong> <%= booking.end_at %></p>
              <p> <strong>Total price: </strong><%= booking.total_price %></p>
              <div class="text-danger">
              <%= link_to "Show",parking_spot_booking_path(booking.parking_spot_id, booking.id),  class: "btn btn-primary" %>
              <%= link_to "Chat",booking_chat_rooms_path(booking.id),  class: "btn btn-primary", target: "_blank" %>
              </div>
            </div>
          <% end %>
        <% end %>
      <hr>
    </div>

    <div class="col-xs-12 col-md-4 col-lg-4 py2" style="border: 1px solid grey;">
      <h2>Previous bookings </h2>
      <hr>
      <% current_user.bookings.each do |booking| %>
        <% if booking.start_at < Date.today && booking.end_at < Date.today %>
          <p>  <%= booking.user.first_name %> </p>
          <p>  <%= booking.parking_spot.street_address.titleize %> </p>
          <p>  <%= booking.start_at %> </p>
          <p>  <%= booking.end_at %> </p>
          <%= link_to "Leave a review", new_booking_review_path(booking), class: "btn btn-primary" %>
          <hr>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="digg_pagination">
        <%= will_paginate @bookings %>
      </div>
    </div>
  </div>

</div><!-- end container -->

app/views/bookings/new.html.erb
    <div class="container-fluid text-center">
      <div class="row bg-grey">
        <div class="col-lg-12 bg-grey">
          <div id="map" style="width: 100%; height: 300px;"></div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row bg-grey">
        <div class="col-lg-6 booking-form-info py2 px2">
          <h2 id="bookingtitle">
            <strong><%= @parking_spot.street_address.upcase %></strong>
          </h2>
          <table class="table table-hover">
            <tbody>
              <tr>
                <td>
                  <strong>Address:</strong>
                </td>
                <td>
                  <%= @parking_spot.street_address.titleize %>
                </td>
              </tr>
              </tr>
              <tr>
                <td>
                  <strong>Description:</strong>
                </td>
                <td>
                  <%= @parking_spot.description %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>City:</strong>
                </td>
                <td>
                  <%= @parking_spot.city.capitalize %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Country:</strong>
                </td>
                <td>
                  <%= @parking_spot.country.capitalize %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Number of spots:</strong>
                </td>
                <td>
                  <%= @parking_spot.number_of_spots %>
                </td>
              </tr>
            </tbody>
          </table>
          <!-- <h3> <%= @parking_spot.street_address %></h3>
          <h3><strong>Description:</strong> <%#= @parking_spot.description %></h3>
          <h3><strong>City:</strong> <%#= @parking_spot.city %></h3>
          <h3><strong>Country:</strong> <%#= @parking_spot.country %></h3>
          <h3><strong>Number of spots:</strong> <%#= @parking_spot.number_of_spots %></h3> -->
        </div>
        <div class="col-lg-3 bg-navy booking-form-book py2">
          <h2><strong>Total Price: </strong>$<span id='total-price'><%= @parking_spot.price %></span></h2>
          <p><strong>Price: </strong><%= @parking_spot.price %> /day</p>
          <%= simple_form_for [@parking_spot, @booking] do |f| %>
            <%= f.input :start_at, as: :string, input_html: { class: 'datepicker', id: "dp_start_at", required: "" } %>
            <%= f.input :end_at, as: :string, input_html: { class: 'datepicker', id: "dp_end_at" } %>
            <%= button_tag(type: 'submit', class: "btn-block btn btn-warning") do %>
              <i class="icon-ok icon-white"></i> Make a Request
            <% end %>
          <% end %>
          <% if current_user.customer_id == nil %>
            <p> Your credit card won't be charged </p>
          <% else %>
            <p> </p>
        <% end %>
      </div>
      <div class="col-lg-3 bg-grey booking-form-info py2 px2">
        <p class="my1">
          <strong>Got a spare driveway or garage in Lebanon?</strong>
        </p>
        <p>
          You can list your parking space for free with Parkingfind. It only takes a few minutes to get up and running, and you could be making money in no time. Find out more here.
        </p>
        <%= link_to "Rent your space", new_parking_spot_path, class: "btn btn-info btn-block my1" %>
      </div>
    </div>
  </div>

<%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyBAbVBfyj-wKN5_BQGC7LsP8hjV2GuH_WE" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).ready(function(){
              $('.datepicker').datepicker({
              todayHighlight: true,
              datesDisabled: <%= raw @parking_spot.unavailable_dates %>,
              startDate: 'today',
              format: "dd/mm/yyyy"
              });
                var base_price = <%= @parking_spot.price %>;
                var parking_spot_price = <%= @parking_spot.price %>
                $('.datepicker').on('change', function(){
                  var start_at = $('#dp_start_at').datepicker('getDate');
                  var end_at = $('#dp_end_at').datepicker('getDate');
                  if (start_at && end_at){
                    var elapsed_time_days = (end_at - start_at) / 86400000;
                    var total_price = base_price + (elapsed_time_days * parking_spot_price)
                    $('#total-price').html(total_price);
                  }
                });
            });

            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(
                [{
                  "lat": <%= @parking_spot.latitude %>,
                  "lng": <%= @parking_spot.longitude %>
                }]
              );
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(13);
              }
            });
      <% end %>
  <% end %>
</div>

app/views/bookings/rejected.js.erb
$('.booking-<%= @booking.id %>').remove();

$('.booking-cancel-<%= @booking.id %>').hide();

var new_confirm = $("<%= j render 'bookings/access', booking: @booking %>")
$('.cancel').append(new_confirm);

app/views/bookings/show.html.erb
<div class='container'>
  <h1>Booking Details</h1>
  <hr>

  <div class="container pb2">
    <p><strong>Id: </strong><%= @booking.id %></p>
    <p><strong>Starts on the: </strong><%= @booking.start_at %></p>
    <p><strong>Ends on the: </strong><%= @booking.end_at %></p>
    <p class='mb0'><strong>Your booking total price is: </strong><%= @booking.total_price %></p>
    <p class='mt0'><small>*You will be debited once the confirmation is approved by the owner</small></p>
    <p><strong>Status: </strong><%= @booking.status %></p>
    <%= link_to 'Back', parking_spot_bookings_path(@booking) , style: "color:green" %>
  </div>

</div>

app/views/bookings/update.html.erb
<h1>Booking#update</h1>
<p>Find me in app/views/booking/update.html.erb</p>