config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :notifications, only: [ :destroy, :index ]

  resources :parking_spots do
    resources :bookings do
      resources :payments, only: [:new, :create]
    end
  end

  resources :bookings, only: [:index] do
    member do
      get "rejected"
      get 'accepted' => 'payments#accepted'
    end
      resource :chat_rooms, only: [:show]
      resources :reviews, only: [:new, :create]
  end

  get '/management' => 'users#management'
  get '/profile' => 'users#show', as: :profile
  get '/search' => 'parking_spots#search'
  mount ActionCable.server => '/cable'

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, PhotoUploader
  after_create :send_welcome_email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]


  has_many :bookings, dependent: :destroy
  has_many :parking_spots, dependent: :destroy
  has_many :reviews, through: :bookings

  has_many :messages, dependent: :destroy

  has_many :notifications, dependent: :destroy

  def name
    email.split('@')[0]
  end


  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  private

#sending welcome mail
  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]
  def create
    resource = User.find_for_database_authentication(email: params[:user][:email])
    return invalid_login_attempt unless resource

    if resource.valid_password?(params[:user][:password])
      sign_in :user, resource
      return render js: "alert('test')";
    end

    invalid_login_attempt
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def invalid_login_attempt
    set_flash_message(:alert, :invalid)
    render json: flash[:alert], status: 401
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def management
    @user = current_user
    @parking_spots = @user.parking_spots
    @segment = ParkingSpot.paginate(:page => params[:page], :per_page => 4)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_cashdone.html.erb
  <div class="row text-center">
    <div class="col-xs-12 col-md-6 col-lg-3">
      <h4> Total of bookings days </h4>
        <% array_of_days = @user.parking_spots.map do |p| %>
        <% p.bookings.sum(:number_of_days) %>
        <% end %>
      <p> <%= array_of_days.inject(:+) %> </p>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-3">
      <h4> Cash earned </h4>
      <% array_of_price = @user.parking_spots.map do |p| %>
        <% p.bookings.sum_price %>
      <% end %>
      <p> <%= humanized_money_with_symbol array_of_price.inject(:+) / 100 %> </p>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-3">
      <h4> Number of parking spots </h4>
      <p> <%= @user.parking_spots.count %> </p>
    </div>
      <div class="col-xs-12 col-md-6 col-lg-3">
        <h4> Number of transactions </h4>
        <% array_of_transaction = @user.parking_spots.map do |p| %>
         <% p.bookings.count %>
        <% end %>
        <p> <%= array_of_transaction.inject(:+) %> </p>
    </div>
  </div>

app/views/users/management.html.erb
<div class="container owner_dashboard">
  <%= render 'cashdone' %>
  <div class="row text-center">
    <div class="col-xs-12, col-lg-6 management-spot">
      <h2> Parking spaces currently rented </h2>
      <% current_user.parking_spots.each do |p| %>
        <% p.bookings.each do |b| %>
          <% if (b.end_at >= Date.today && b.status == "paid") %>
            <hr>
            <div class="management-info-button">
              <div class="management-info">
                <p><strong> Address: </strong><%= b.parking_spot.street_address %> </p>
                <p><strong> Total Price: </strong> <%= humanized_money_with_symbol b.total_price %></p>
                <p><strong>Start: </strong> <%= b.start_at %> </p>
                <p><strong>End: </strong><%= b.end_at %> </p>
              </div>

            <div class="management-button">
              <% if b.status == "paid" || b.status == "accepted" %>
                <p>
                  <%= link_to "Chat", booking_chat_rooms_path(b), class: "btn btn-info", target: "_blank", style: "width: 200px;" %>
                </p>
                <p>
                  <%= link_to accepted_booking_path(b), remote: true, class: "booking-confirm-#{b.id} btn btn-success", style: "width: 200px;" do %>
                    Confirmed
                  <% end %>
                </p>
                <p>
                  <%= link_to rejected_booking_path(b), remote: true, class: "booking-cancel-#{b.id} btn btn-danger", style: "width: 200px;" do %>
                    Cancelled
                  <% end %>
                </p>
              <% end %>

              <% if b.status == "rejected" %>
                <p>
                  <%= link_to "Chat", booking_chat_rooms_path(b), class: "btn btn-danger", target: "_blank" %>
                </p>
              <% end %>
            <% end %>
            </div>
          </div>
          <% end %>
        <% end %>
    </div>
    <div class="management-spot">
      <h2> Statistics on your parkings </h2>
        <% if current_user.parking_spots.empty? %>
          <h2> You don't have any parking spots yet ! </h2>
        <% else %>
                  <% current_user.parking_spots.each do |parking_spot| %>
                    <hr>
                    <div class="management-info-button">
                    <div class="management-info">
                      <p> <strong> Address: </strong> : <%= parking_spot.street_address %> </p>
                      <p> <strong> Price: </strong> <%= humanized_money_with_symbol parking_spot.price %> </p>
                      <p> <strong> Total Number of booking: </strong><%= parking_spot.bookings.count %> </p>
                      <p> <strong> Total Cash earned </strong><%= humanized_money_with_symbol parking_spot.bookings.sum_price / 100 %> </p>
                      <p> <strong> Total days booked </strong> <%= parking_spot.bookings.sum(:number_of_days) %> </p>
                      <p> <strong> ID: </strong> <%= parking_spot.id %> </p>
                    </div>
                    <div class="management-button">
                      <% if parking_spot.bookings.empty? %>
                        <p> <%= link_to "Edit", edit_parking_spot_path(parking_spot), class: "btn btn-info" %></p>
                        <p> <%= link_to 'Details', parking_spot_path(parking_spot), class:"btn btn-success" %> </p>
                        <p> <%= link_to "Delete Parking", parking_spot_path(parking_spot), { class: "btn btn-danger", method: :delete }  %></p>
                      <% else %>
                        <p> <%= link_to "Edit", edit_parking_spot_path(parking_spot), class: "btn btn-info" %></p>
                        <p> <%= link_to 'Details', parking_spot_path(parking_spot), class:"btn btn-success" %> </p>
                      <% end %>
                    </div>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
    </div>
  </div>


    <div class="digg_pagination">
      <%= will_paginate @segment %>
    </div>
</div>

app/views/users/show.html.erb
<div class="wrapper" style="min-height: 77vh !important;height: 77vh !important;">
    <div class="sidebar">
      <div class="sidebar-wrapper">
            <div class="logo">
                <a  class="simple-text">
                  Dashboard
                </a>
            </div>
            <ul class="nav">
                <li class="active">
                    <a href="#">
                        <p>Analytics</p>
                    </a>
                </li>
                <li>
                    <%= link_to parking_spots_path do %>
                        <p>Book A Place</p>
                    <% end %>
                </li>
                <% if !@user.bookings.empty? %>
                  <li>
                    <%= link_to bookings_path do %>
                      <p>View My Bookings</p>
                    <% end %>
                  </li>
                <% end %>
                <% if !@user.parking_spots.empty? %>
                  <li>
                    <%= link_to management_path do %>
                      <p>Manage My Parkings</p>
                    <% end %>
                  </li>
                <% end %>
                <li>
                  <%= link_to new_parking_spot_path do %>
                    <p>Create A Parking Spot</p>
                  <% end %>
                </li>
            </ul>
      </div>
  </div>
  <% if user_signed_in? %>
    <div class="main-panel">
          <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6" style="height:600px">
                        <div class="card">
                            <div class="header">
                                <h4 class="title"></h4>
                                <p class="category"></p>
                            </div>
                            <h2 style="text-align:center;font-weight: 500;font-family: Lato;padding-bottom: 13px;">Parking Spot</h2>
                            <div class="content row">
                              <div class="col-md-6" style="padding-bottom: 45px;">
                                <div class='dashboard-element'>
                                  <h4 class="title text-center" style="color: #5f5b63;font-family: lato;">Spaces owned</h4>
                                  <p class="text-center"><%= @user.parking_spots.count %></p>
                                </div>
                              </div>
                            <% if !@user.parking_spots.empty? %>
                              <div class="col-md-6" style="padding-bottom: 45px;">
                                <div class='dashboard-element'>
                                  <h4 class="title text-center" style="color: #5f5b63;font-family: lato;">Books Count</h4>
                                  <% array_of_days = @user.parking_spots.map do |p| %>
                                    <% p.bookings.sum(:number_of_days) %>
                                  <% end %>
                                    <p class="text-center">
                                      <%= array_of_days.inject(:+) %>
                                    </p>
                                </div>
                              </div>
                            <% end %>
                                <div class="col-md-6" style="padding-bottom: 45px;">
                                  <div class='dashboard-element'>
                                    <h4 class="title text-center" style="color: #5f5b63;font-family: lato;">Cash Earned</h4>
                                    <% array_of_price = @user.parking_spots.map do |p| %>
                                      <% p.bookings.sum_price / 100 %>
                                    <% end %>
                                    <p class="text-center">$<%= (array_of_price.inject(:+).to_i) / 100 %></p>
                                  </div>
                                </div>
                              <% if !@user.parking_spots.empty? %>
                                <div class="col-md-6" style="padding-bottom: 45px;">
                                </div>
                              <% end %>
                                <div class="footer">
                                    <hr>
                                    <div class="stats">
                                      <% if current_user.parking_spots.empty?  %>
                                        <% a  = DateTime.now %>
                                        <% if current_user.parking_spots.last != nil %>
                                          <% b = current_user.parking_spots.last.created_at %>
                                          <% c = a.to_date - b.to_date %>
                                          <i class="fa fa-clock-o"></i><%= pluralize(c.to_i, 'day') %> ago
                                        <% end %>
                                      <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card">
                            <div class="header">
                              <h4 class="title"></h4>
                              <p class="category"></p>
                            </div>
                            <h2 style="text-align:center;font-weight: 500;font-family: Lato;padding-bottom: 13px;">Booking</h2>
                            <div class="content row">
                                <div class="col-md-6" style="padding-bottom: 45px;">
                                  <div class='dashboard-element'>

                                    <h4 class="title text-center" style="color: #5f5b63;font-family: lato;">Cash Spent</h4>
                                    <p class="text-center">$<%= current_user.bookings.sum_price / 100 %></p>

                                  </div>
                                </div>
                                <div class="col-md-6" style="padding-bottom: 45px;">
                                  <div class='dashboard-element'>
                                    <h4 class="title text-center" style="color: #5f5b63;font-family: lato;">Transactions Count</h4>
                                    <p class="text-center"><%= current_user.bookings.count %></p>
                                  </div>
                                </div>
                                <div class="col-md-6" style="padding-bottom: 45px;">

                                </div>
                                <div class="footer">
                                    <hr>
                                    <div class="stats">
                                      <% if current_user.parking_spots.empty?  %>
                                        <% if current_user.parking_spots.last != nil %>
                                          <% e  = DateTime.now %>
                                          <% f = current_user.bookings.last.created_at %>
                                          <% cg= e.to_date - f.to_date %>
                                          <i class="fa fa-history"></i> Updated <%= pluralize(cg.to_i, 'day') %> ago
                                        <% end %>
                                      <% end %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>