config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :notifications, only: [ :destroy, :index ]

  resources :parking_spots do
    resources :bookings do
      resources :payments, only: [:new, :create]
    end
  end

  resources :bookings, only: [:index] do
    member do
      get "rejected"
      get 'accepted' => 'payments#accepted'
    end
      resource :chat_rooms, only: [:show]
      resources :reviews, only: [:new, :create]
  end

  get '/management' => 'users#management'
  get '/profile' => 'users#show', as: :profile
  get '/search' => 'parking_spots#search'
  mount ActionCable.server => '/cable'

end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
        <section id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block">
                            <div class="footer-contant">
                                <h3>Say Hi, Get In Touch</h3>
                                <div class="social-icon">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-google"></i></a>
                                    <a href="#"><i class="fa fa-youtube"></i></a>
                                </div>
                                <div class="support-link">
                                    <ul>
                                        <li><a href="#">Contact</a></li>
                                        <li><a href="#">Developers</a></li>
                                        <li><a href="#">Privacy</a></li>
                                    </ul>
                                </div>
                                <div class="text-center">
                                  <p style="color:#8C9494;padding-top:30px">© 2016 Parking Find, Inc.</p>
                                </div>
                            </div>
                        </div>
                    </div><!-- col-md-12 -->
                </div><!-- .row -->
            </div><!-- .container -->
        </section><!-- #footer -->

app/views/shared/_navbar.html.erb
        <section id="header" style="background: #f1f1f1 ;padding: 0px 0px;">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="block-left">
                          <nav class="navbar navbar-default" role="navigation">
                            <div class="container-fluid" style="background: #f1f1f1">
                            <div class="navbar-header">
                              <div class="nav-logo">
                                <%= link_to root_path, style: "color:black !important" do %>
                                  <%= image_tag "logo.png", style: "width:200px" %>
                                <% end %>
                              </div>
                            </div>
                            </div>
                          </nav>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="block-right">
                            <div class="contact-area">
                                <ul>

                                    <% if user_signed_in? %>
                                      <% if current_user.notifications.count != 0 %>
                                        <li>

                                            <div class="badge-container">
                                              <i class="fa fa-bell"></i>
                                              <div class="badge badge-blue"><%= current_user.notifications.count %></div>
                                            </div>

                                        </li>
                                      <% end %>
                                    <% end %>


                                      <li>
                                       <% if user_signed_in? %>
                                          <div class="navbar-wagon-item">
                                            <div class="dropdown">
                                              <% if current_user.avatar_url %>
                                                <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                                              <% elsif current_user.facebook_picture_url %>
                                                <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
                                              <% else %>
                                                <%= image_tag "https://x.myspacecdn.com/new/common/images/user.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                                              <% end %>

                                              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                                                <li>
                                                  <%= link_to profile_path do %>
                                                    <i class="fa fa-user"></i>  <%= t(".profile", default: "Dashboard") %>
                                                  <% end %>
                                                </li>
                                                <li>
                                                  <%= link_to edit_user_registration_path do %>
                                                    <i class="fa fa-home"></i>  <%= t(".profile", default: "Edit Profile") %>
                                                  <% end %>
                                                </li>
                                                <li>
                                                  <%= link_to destroy_user_session_path, method: :delete do %>
                                                    <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                                                  <% end %>
                                                </li>
                                              </ul>
                                            </div>
                                          </div>
                                          <% else %>
                                            <%= button_tag t(".sign-up", default: "Sign Up") , class: "navbar-wagon-item navbar-wagon-link", data: { toggle: 'modal',  target: '#modal-sign-up' } %>

                                            <%= button_tag t(".sign_in", default: "Login") , class: "navbar-wagon-item navbar-wagon-link", id: "losgg", data: { toggle: 'modal',  target: '#modal-login' } %>

                                          <% end %>
                                        </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

app/views/shared/_notifications.html.erb
<% if current_user != nil %>
  <% current_user.notifications.each do |notification| %>
      <div class="alert alert-success alert-dismissible" role="alert" id="noti-<%= notification.id %>" >
        <%= link_to notification_path(notification),  class: "close", method: :delete, remote: true do  %>
          <span>&times;</span>
        <% end %>
        <%= notification.content.html_safe %>
    </div>
  <% end %>
<% end %>