config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :notifications, only: [ :destroy, :index ]

  resources :parking_spots do
    resources :bookings do
      resources :payments, only: [:new, :create]
    end
  end

  resources :bookings, only: [:index] do
    member do
      get "rejected"
      get 'accepted' => 'payments#accepted'
    end
      resource :chat_rooms, only: [:show]
      resources :reviews, only: [:new, :create]
  end

  get '/management' => 'users#management'
  get '/profile' => 'users#show', as: :profile
  get '/search' => 'parking_spots#search'
  mount ActionCable.server => '/cable'

end

app/models/parking_spot.rb
class ParkingSpot < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  #validates :latitude, :longitude, presence: true


  monetize :price_cents


  # geocoded_by :street_address
  # after_validation :geocode, if: :street_address_changed?

  def unavailable_dates
    impossible_dates = []
    date_ranges = self.bookings.map { |x| (x.start_at..x.end_at)}
    date_ranges.each do |range|
      range.map do |date|
        impossible_dates << date.strftime("%d/%m/%Y")
      end
    end
    impossible_dates
  end



end

app/controllers/parking_spots_controller.rb
class ParkingSpotsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [ :index, :search ]
  before_action :find_user

  def index
    @parking_spots = ParkingSpot.all

    @parking_spots = ParkingSpot.where.not(latitude: nil, longitude: nil)
    @parking_spots = @parking_spots.paginate(:page => params[:page], :per_page => 4)

    @hash = Gmaps4rails.build_markers(@parking_spots) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  def show
    @parking_spot = ParkingSpot.find(params[:id])
    # @parking_spot = current_user.parking_spots.find_by(id: params[:id])
    # @parking_spots = ParkingSpot.where.not(latitude: nil, longitude: nil)
    @parking_spot_coordinates = { lat: @parking_spot.latitude, lng: @parking_spot.longitude }
    @hash = Gmaps4rails.build_markers(@parking_spots) do |parking, marker|
      marker.lat parking.latitude
      marker.lng parking.longitude
    end

    # redirect_to profile_path unless @parking_spot
  end

  def new
    @parking_spot = ParkingSpot.new
  end

  def create
    @parking_spot = @user.parking_spots.build(parking_params)
    @parking_spot.save
    redirect_to parking_spot_path(@parking_spot)
  end

  def edit
    @parking_spot = current_user.parking_spots.find_by(id: params[:id])
    redirect_to root_path unless @parking_spot
  end

  def update
    @parking_spot = ParkingSpot.find(params[:id])
    @parking_spot.update(parking_params)
    # redirect_to articles_path
  end

  def destroy
    @parking_spot = ParkingSpot.find(params[:id])
    @parking_spot.destroy
    redirect_to profile_path
  end

  def search
    #perform your search
    @parking_spots = ParkingSpot.all.where("city ILIKE ? OR country ILIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
    @parking_spots = @parking_spots.paginate(page: params[:page], per_page: 4)

    @hash = Gmaps4rails.build_markers(@parking_spots) do |parking, marker|
      marker.lat parking.latitude
      marker.lng parking.longitude
    end
  end

  private

  def find_user
    @user = current_user
  end

  def parking_params
    params.require(:parking_spot).permit(:street_address, :city, :country, :latitude, :longitude, :user_id, :price, :type, :number_of_spots, :description, :photo, :photo_cache)
  end
end

app/helpers/parking_spots_helper.rb
module ParkingSpotsHelper
end

app/views/parking_spots/_createspot.html.erb
<!-- Modal -->
<div id="rentspace" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create a parking spot</h4>
      </div>

      <div class="modal-body">
        <%= simple_form_for(@parking_spot) do |f| %>
          <div class="create_primary">
            <h4> WHERE IS YOUR PARKING SPACE? </h4>
            <hr>
                <div id="map_set_location" class="map_structure" style="width: 100%;height: 200px;position: fixed !important;">
              </div>

            <div class="form-group">
            <div>
              <%= f.input :latitude, as: :hidden %>
              <%= f.input :longitude, as: :hidden %>
            </div>
              <div> <%= f.label :street_address %> </div>
              <div> <%= f.text_field :street_address, class: "form-control" %> </div>
            </div>
            <br>

            <div class="row">
              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <div><%= f.label :city %></div>
                  <div><%= f.text_field :city, class: "form-control" %></div>
                </div>
              </div>

              <div class="col-xs-12 col-sm-6">
                <div class="form-group">
                  <div><%= f.label :country %></div>
                  <div>
                    <%= f.text_field :country, class: "form-control" %>
                  </div>
                </div>
              </div>
            </div><!-- end row for city and country -->
          </div>

        <div class="create_important">
          <h4> ABOUT YOUR SPACE </h4>
          <hr>
          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <div> <%= f.label :price %> </div>
                <div> <%= f.text_field :price, class:"form-control" %> </div>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <div> <%= f.label :number_of_spots %> </div>
                <div> <%= f.text_field :number_of_spots, class: "form-control"  %> </div>
              </div>
            </div>
          </div>
        </div>

          <div class="create_description">
            <h4> ADD A DESCRIPTION </h4>
            <div>
              <!-- <div id="map_set_location" class="map_structure" style="width: 100%;height: 230px;position: fixed !important;">
              </div> -->
            </div>
            <hr>
            <div> <%= f.label :description %> </div>
            <div> <%= f.text_field :description, class:"form-control" %> </div>
          </div>

          <div class="create_photo">
            <h4> ADD A PICTURE </h4>
            <hr>
            <div> <%= f.input :photo %> </div>
            <div> <%= f.input :photo_cache, as: :hidden %> </div>
          </div>

          <div class="form-actions ">
            <%= f.button :submit, "Create",:class => "btn-block btn-primary" %>
          </div>
          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>






<%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyBAbVBfyj-wKN5_BQGC7LsP8hjV2GuH_WE" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>



<% content_for(:after_js) do %>
  <%= javascript_tag do %>

    var map;
    var marker;

// geolocation with HTML5 through browser
     if (navigator.geolocation) {

        navigator.geolocation.getCurrentPosition(function(p){
        console.log(p.coords.longitude);
          var mapOptions = {
          center: new google.maps.LatLng({lng: p.coords.longitude,lat: p.coords.latitude}),
          zoom: 14
          }
          initMap(mapOptions);
          });
    } else {
      var mapOptions = {
        center: new google.maps.LatLng(-25.363, 131.044),
        zoom: 14
        }
      initMap(mapOptions);
       }


      function initMap(mapOptions) {

        var handler = Gmaps.build('Google');

        handler.buildMap({ provider: mapOptions, internal: { id: 'map_set_location' } }, function() {
          map = handler.getMap();
          map.addListener('click', function(e) {
            addMarker(e.latLng);
          });
        });
      }

      function addMarker(latLng){
        if (marker) marker.setMap(null);
        marker = new google.maps.Marker({
          position: latLng,
          map: map
        });
        $('#parking_spot_latitude').val(latLng.lat());
        $('#parking_spot_longitude').val(latLng.lng());
      }
  <% end %>
<% end %>

app/views/parking_spots/_whyrent.html.erb
<div class="container-fluid text-center how-create bg-navy">
<h2> <strong> Rent your space! </strong> </h2>
  <div class="row ">
    <div class="mt3">
      <div class="col-lg-4">
         <%= image_tag 'map.svg', class:"home-picture-big-create" %>
        <h2> <strong> List your space for free  </strong></h2>
        <p> You can add a driveway, car park, empty hotel spaces or anything else </p>
      </div>
       <div class="col-lg-4">
        <%= image_tag 'calendar.svg', class:"home-picture-big-create" %>
        <h2> <strong> Control availability </strong></h2>
        <p> Validate each of the request to be sure that it fits your needs</p>
      </div>
       <div class="col-lg-4">
        <%= image_tag 'dollar.svg', class:"home-picture-big-create" %>
        <h2><strong> Get paid </strong></h2>
        <p> Get regular bookings and payments straight to your bank or paypal account</p>
      </div>
    </div>
  </div>
</div>

app/views/parking_spots/destroy.html.erb
<h1>ParkingSpots#destroy</h1>
<p>Find me in app/views/parking_spots/destroy.html.erb</p>

app/views/parking_spots/edit.html.erb
<div class="container-fluid text-center">
<h1> Edit your parking space </h1>
  <div class="raw">
    <div class="col-lg-6">
      <%= simple_form_for(@parking_spot) do |f| %>
      <div class="">
        <h4> WHERE IS YOUR PARKING SPACE? </h4>
        <hr>
        <div class="form-group">
          <div>
            <%= f.input :latitude, as: :hidden %>
            <%= f.input :longitude, as: :hidden %>
          </div>
          <div>
            <%= f.label :street_address %>
          </div>
          <div>
            <%= f.text_field :street_address, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <div><%= f.label :city %></div>
              <div><%= f.text_field :city, class: "form-control" %></div>
            </div>
          </div>

          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <div><%= f.label :country %></div>
              <div>
                <%= f.text_field :country, class: "form-control" %>
              </div>
            </div>
          </div>
        </div><!-- end row for city and country -->
      </div>
      <div class="">
        <h4> ABOUT YOUR SPACE </h4>
        <hr>
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <div> <%= f.label :price %> </div>
              <div> <%= f.text_field :price, class:"form-control" %> </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <div> <%= f.label :number_of_spots %> </div>
              <div> <%= f.text_field :number_of_spots, class: "form-control"  %> </div>
            </div>
          </div>
        </div>
      </div>

      <div class="">
        <h4> ADD A DESCRIPTION </h4>
        <hr>
        <div> <%= f.label :description %> </div>
        <div> <%= f.text_field :description, class:"form-control" %> </div>
      </div>

      <div class="">
        <h4> ADD A PICTURE </h4>
        <hr>
        <div> <%= f.input :photo %> </div>
        <div> <%= f.input :photo_cache, as: :hidden %> </div>
      </div>

      <div class="form-actions ">
        <%= f.button :submit, "Create",:class => "btn-block btn-primary" %>
      </div>
      <% end %>
    </div>
    <div class="col-lg-6">
      <h4> SET THE LOCATION OF YOUR SPACE </h4>
      <hr>
      <div id="map_set_location" class="map_structure" style="width: 100%;height: 500px;position: fixed !important;">
      </div>
    </div>
  </div>
</div>
<br>



<%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyBAbVBfyj-wKN5_BQGC7LsP8hjV2GuH_WE" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>



<% content_for(:after_js) do %>
  <%= javascript_tag do %>

    var map;
    var marker;

// geolocation with HTML5 through browser
     if (navigator.geolocation) {

        navigator.geolocation.getCurrentPosition(function(p){
        console.log(p.coords.longitude);
          var mapOptions = {
          center: new google.maps.LatLng({lng: p.coords.longitude,lat: p.coords.latitude}),
          zoom: 14
          }
          initMap(mapOptions);
          });
    } else {
      var mapOptions = {
        center: new google.maps.LatLng(-25.363, 131.044),
        zoom: 14
        }
      initMap(mapOptions);
       }


      function initMap(mapOptions) {

        var handler = Gmaps.build('Google');

        handler.buildMap({ provider: mapOptions, internal: { id: 'map_set_location' } }, function() {
          map = handler.getMap();
          map.addListener('click', function(e) {
            addMarker(e.latLng);
          });
        });
      }

      function addMarker(latLng){
        if (marker) marker.setMap(null);
        marker = new google.maps.Marker({
          position: latLng,
          map: map
        });
        $('#parking_spot_latitude').val(latLng.lat());
        $('#parking_spot_longitude').val(latLng.lng());
      }
  <% end %>
<% end %>

app/views/parking_spots/index.html.erb
  <div class='text-left' style="background: #005866;">
    <form action='/search' id='form_container' class='form-inline' style="padding: 10px;">
    <div class='form-group'>
      <label for='search'><label>
      <input id="search_box" type='text' name='search' class='form-control' placeholder= 'Where to park?'>
      <input class="btn btn-success" type='submit' value='Search' id="input-formm">
    </div>
  </form>
  </div>
<div class="container-fluid" style="background-color:##f9f1f1">
  <div class="row">
    <div class="col-xs-12 col-lg-4" style="height: 100%;overflow: hidden;overflow-y: scroll;padding-left: 0px;padding-right:0pc">
      <div class="scroll container" style="background: #eae7e7;">
        <% if @parking_spots.blank? %>
          <h3>No parking spots available</h3>
        <% else %>
          <% @parking_spots.each do |parking_spot| %>
            <div class="row" style="border: 1px solid;">
              <div class="col-xs-6 col-lg-2" style="margin-left: 13px;">
                <h6><strong>Address:</strong> <%= parking_spot.street_address %></h6>
                <h6><strong>City:</strong> <%= parking_spot.city %></h6>
                <h6><strong>Country:</strong> <%= parking_spot.country %></h6>
              </div>

              <div class="col-xs-6 col-lg-2" style="margin-right: 13px;" id="resppp">

              <h2 style="position:relative;left:33px;top:20px">
                $<%= parking_spot.price.to_i %>
              </h2>
              <%= link_to new_parking_spot_booking_path(parking_spot), style: 'color: black;' do %>
                <button style="position:relative;left:14px;top:20px;padding: 7px;background: white;border: none;">
                  Make a request
                </button>
              <% end %>


              </div>
            </div>
          <% end %>
        <% end %>
        <div class="digg_pagination" style="background:transparent;">
          <%= will_paginate @parking_spots %>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-lg-8" id="smappux" style="padding-left: 0px;padding-right: 0px;">
      <div id="map" class="map_structure" style="width: 100%;height: 530px;position: fixed !important;"></div>
    </div>
  </div>
</div>

<%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyBAbVBfyj-wKN5_BQGC7LsP8hjV2GuH_WE" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        if ("lat" != null) {

        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
         }
          if (markers.length == 0) {
            handler.getMap().setZoom(2);
          }
          else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
      });
  <% end %>
<% end %>

app/views/parking_spots/new.html.erb
<div class="container-fluid">
  <div class="create-button text-center" id="image_park">
    <button type="button" class="btn btn-default btn-lg"  id='btn-create-spot' style="margin-top: 83px;" data-toggle="modal" data-target="#rentspace">Create Parking Spot</button>
  </div>
</div>
  <%= render "whyrent" %>

  <%= render "createspot" %>

app/views/parking_spots/search.html.erb
<div class='text-left' style="background: #005866;">
    <form action='/search' id='form_container' class='form-inline' style="padding: 10px;">
    <div class='form-group'>
      <label for='search'><label>
      <input id="search_box" type='text' name='search' class='form-control' placeholder= 'Where to park?'>
      <input class="btn btn-success" type='submit' value='Search' id="input-formm">
    </div>
  </form>
  </div>
<div class="container-fluid" style="background-color:##f9f1f1">
  <div class="row">
    <div class="col-xs-12 col-lg-4" style="height: 100%;overflow: hidden;overflow-y: scroll;padding-left: 0px;padding-right:0pc">
      <div class="scroll container" style="background: #eae7e7;">
        <% if @parking_spots.blank? %>
          <h3>No parking spots available</h3>
        <% else %>
          <% @parking_spots.each do |parking_spot| %>
            <div class="row" style="border: 1px solid;">
              <div class="col-xs-6 col-lg-2" style="margin-left: 13px;">
                <h6><strong>Address:</strong> <%= parking_spot.street_address %></h6>
                <h6><strong>City:</strong> <%= parking_spot.city %></h6>
                <h6><strong>Country:</strong> <%= parking_spot.country %></h6>
              </div>

              <div class="col-xs-6 col-lg-2" style="margin-right: 13px;" id="resppp">

              <h2 style="position:relative;left:33px;top:20px">
                $<%= parking_spot.price.to_i %>
              </h2>
              <button style="position:relative;left:14px;top:20px;padding: 7px;background: white;border: none;">
                <%= link_to 'Book now!',  new_parking_spot_booking_path(parking_spot), style: 'color: black;' %>
              </button>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="digg_pagination" style="background:transparent;">
          <%= will_paginate @parking_spots %>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-lg-8" id="smappux" style="padding-left: 0px;padding-right: 0px;">
      <div id="map" class="map_structure" style="width: 100%;height: 530px;position: fixed !important;"></div>
    </div>
  </div>
</div>

<%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyBAbVBfyj-wKN5_BQGC7LsP8hjV2GuH_WE" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        if ("lat" != null) {

        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
         }
          if (markers.length == 0) {
            handler.getMap().setZoom(2);
          }
          else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
      });
  <% end %>
<% end %>

app/views/parking_spots/show.html.erb
<div class="container-fluid text-center">
      <div class="row bg-grey">
        <div class="col-lg-12 bg-grey">
          <div id="map" style="width: 100%; height: 300px;"></div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row bg-grey">
        <div class="col-lg-6 booking-form-info py2 px2">
          <h2 id="bookingtitle">
            <strong><%= @parking_spot.street_address.upcase %></strong>
          </h2>
          <table class="table table-hover">
            <tbody>
              <tr>
                <td>
                  <strong>Address:</strong>
                </td>
                <td>
                  <%= @parking_spot.street_address.titleize %>
                </td>
              </tr>
              </tr>
              <tr>
                <td>
                  <strong>Description:</strong>
                </td>
                <td>
                  <%= @parking_spot.description %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>City:</strong>
                </td>
                <td>
                  <%= @parking_spot.city.capitalize %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Country:</strong>
                </td>
                <td>
                  <%= @parking_spot.country.capitalize %>
                </td>
              </tr>
              <tr>
                <td>
                  <strong>Number of spots:</strong>
                </td>
                <td>
                  <%= @parking_spot.number_of_spots %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-lg-3 bg-navy booking-form-book py2" style="height:100%">
          <h2><strong>Price: </strong>$<span id='total-price'><%= @parking_spot.price %></span>/day</h2>
          <%= link_to 'Dashboard', profile_path, class: 'btn btn-success btn-block' %>
      </div>
      <div class="col-lg-3 bg-grey booking-form-info py2 px2">
        <p class="my1">
          <strong>Got a spare driveway or garage in Lebanon?</strong>
        </p>
        <p>
          You can list your parking space for free with Parkingfind. It only takes a few minutes to get up and running, and you could be making money in no time. Find out more here.
        </p>
        <%= link_to "Rent your space", new_parking_spot_path, class: "btn btn-info btn-block my1" %>
      </div>
    </div>
  </div>

<%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyBAbVBfyj-wKN5_BQGC7LsP8hjV2GuH_WE" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
<%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).ready(function(){
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(
                [{
                  "lat": <%= @parking_spot.latitude %>,
                  "lng": <%= @parking_spot.longitude %>
                }]
              );
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(13);
              }
            });
            });
      <% end %>
  <% end %>
</div>

app/views/parking_spots/update.html.erb
<div class="container text-center">
  <h3>The Parkings Spot was update</h3>
  <br><br><br>
  <div class="content text-left col-md-6">
    <p><strong>Description:</strong> <%= @parking_spot.description %></p>
    <p><strong>City:</strong> <%= @parking_spot.city %></p>
    <p><strong>Country:</strong> <%= @parking_spot.country %></p>
    <p><strong>Price:</strong> <%= @parking_spot.price %></p>
    <p><strong>Number of spots:</strong> <%= @parking_spot.number_of_spots %></p>
    <p><strong>Address:</strong> <%= @parking_spot.street_address %></p>
    <br>
    <button><%= link_to "Back", profile_path %></button>
  </div>

  <div class="text-center col-md-6">
    <%= cl_image_tag @parking_spot.photo, height: 380, width: 500, crop: :fill %>
  </div>
</div>



<br><br>
<br><br>